# Generated by Django 3.2.13 on 2022-10-28 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20221028_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='like_comments',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
